# This workflow will build a Java project with Maven

name: Java CI with Maven

permissions:
  contents: write

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - closed
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Define the release version"
        required: true
        default: ""
      developmentVersion:
        description: "Define the snapshot version"
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
        java-version: 20.0.1
        distribution: 'temurin'
        java-package: 'jdk'
        cache: 'maven'
        server-id: central
    - name: Configure Git User
      run: |
        git config user.email "devops@naturalint.com"
        git config user.name "GitHub Actions"
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v5.0.0
      with:
        gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    - name: Verify Whether a Release is Ready
      id: release
      shell: bash
      run: |
        if [ "${{ github.event.inputs.releaseVersion }}" != "" ] && [ "${{ github.event.inputs.developmentVersion }}" != "" ]; then
          echo "auto_publish=true" >> $GITHUB_ENV
        else
          echo "auto_publish=false" >> $GITHUB_ENV
        fi
    - name: Build PR with Maven
      if: ${{ github.event.pull_request.merged == false }}
      run: |
        mvn clean install
    - name: Release with Maven
      if: ${{ github.event.pull_request.merged == true || github.event_name != 'pull_request' }}
      run: |
        mvn -B -U \
          -Pci-cd \
          release:prepare \
          release:perform \
          javadoc:jar \
          source:jar \
          -s settings.xml \
          -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} \
          -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
          -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} \
          deploy
      env:
        MAVEN_USERNAME: ${{ secrets.MVN_TOKEN_USER }}
        MAVEN_PASSWORD: ${{ secrets.MVN_TOKEN_PASSWORD }}
        AUTO_PUBLISH: ${{ env.auto_publish }}
    - name: Artifact Name
      if: ${{ github.event.pull_request.merged == true || github.event_name != 'pull_request' }}
      shell: bash
      run: |
        echo "artifact_name=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
        echo "group_name=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_ENV
    - name: Define Jar Name
      if: ${{ github.event.pull_request.merged == true || github.event_name != 'pull_request' }}
      shell: bash
      run: |
        mv ./target/${{ env.group_name }}:${{ env.artifact_name }}.jar ./target/${{ env.artifact_name }}.jar
    - name: Upload Artifact
      if: ${{ github.event.pull_request.merged == true || github.event_name != 'pull_request' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifact_name }}-${{ env.sha_short }}
        path: ./target/${{ env.artifact_name }}.jar
    - name: Workflow Release Notes
      if: |
        ${{ github.event.pull_request.merged == true || github.event_name != 'pull_request' }} &&
        ${{ github.event.inputs.releaseVersion }} != "" && ${{ github.event.inputs.developmentVersion }} != ""
      uses: peter-evans/repository-dispatch@v2
      with:
        event-type: release-notes
        client-payload: '{"auto_publish": "${{ env.auto_publish }}", "artifact": "${{ env.artifact_name }}-${{ env.sha_short }}"}'
